version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: threedisplay_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: threedisplay_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
    environment:
      - SECRET_KEY=your-secret-key-keep-it-secret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - UPLOAD_DIR=uploads
      - MAX_UPLOAD_SIZE=104857600
      - ALLOWED_EXTENSIONS=glb,gltf,obj,fbx,jpg,jpeg,png
      - BACKEND_CORS_ORIGINS=http://localhost:5173,http://localhost:8000
      - DB_TYPE=${DB_TYPE:-sqlite}
      - SQLITE_URL=sqlite:///./app.db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db

networks:
  default:
    name: threedisplay_network_dev

volumes:
  postgres_data_dev: