version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - USE_CHINESE_MIRRORS=${USE_CHINESE_MIRRORS:-false}
        - NPM_MIRROR=${NPM_MIRROR:-https://registry.npmjs.org}
      network: ${DOCKER_BUILD_NETWORK:-default}
    container_name: threedisplay_frontend
    ports:
      - "80:80"
    volumes:
      - ./backend/uploads:/usr/share/nginx/html/uploads
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - USE_CHINESE_MIRRORS=${USE_CHINESE_MIRRORS:-false}
        - PYPI_MIRROR=${PYPI_MIRROR:-https://pypi.org/simple}
      network: ${DOCKER_BUILD_NETWORK:-default}
    container_name: threedisplay_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - backend/.env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - UPLOAD_DIR=/app/uploads
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: threedisplay_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    name: threedisplay_network

volumes:
  postgres_data:
    name: threedisplay_postgres_data