version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: threedisplay_frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: threedisplay_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/app.db:/app/app.db
    environment:
      - SECRET_KEY=your-secret-key-keep-it-secret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - UPLOAD_DIR=uploads
      - MAX_UPLOAD_SIZE=104857600
      - ALLOWED_EXTENSIONS=glb,gltf,obj,fbx,jpg,jpeg,png
      - BACKEND_CORS_ORIGINS=http://localhost,http://localhost:80,http://localhost:8000
      - DB_TYPE=${DB_TYPE:-sqlite}
      - SQLITE_URL=sqlite:///./app.db
      # PostgreSQL配置（如果使用PostgreSQL，取消注释）
      #- POSTGRES_SERVER=db
      #- POSTGRES_USER=postgres
      #- POSTGRES_PASSWORD=postgres
      #- POSTGRES_DB=threedisplay
      #- POSTGRES_PORT=5433
    restart: unless-stopped
    depends_on:
      - db

  # PostgreSQL服务（默认不启用，需要时取消注释）
  #db:
  #  image: postgres:15-alpine
  #  container_name: threedisplay_db
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres
  #    - POSTGRES_DB=threedisplay
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #  ports:
  #    - "5433:5432"
  #  restart: unless-stopped

networks:
  default:
    name: threedisplay_network

volumes:
  postgres_data: